Compilation warnings/errors on gas_gauge.sol:
Error: Source "lib/auth/FactoryVerifier.sol" not found: File not found. Searched the following locations: "".
 --> gas_gauge.sol:5:1:
  |
5 | import { FactoryVerifier } from "./lib/auth/FactoryVerifier.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "Types.sol" not found: File not found. Searched the following locations: "".
 --> gas_gauge.sol:6:1:
  |
6 | import { IERC721, IERC1155 } from "./Types.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/platform/solc.py", line 561, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.9.3-py3.8.egg/slither/__main__.py", line 837, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.9.3-py3.8.egg/slither/__main__.py", line 90, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/crytic_compile.py", line 643, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/crytic_compile.py", line 131, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/crytic_compile.py", line 553, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/platform/solc.py", line 156, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/platform/solc.py", line 285, in _get_targets_json
    return _run_solc(
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/platform/solc.py", line 565, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Source "lib/auth/FactoryVerifier.sol" not found: File not found. Searched the following locations: "".
 --> gas_gauge.sol:5:1:
  |
5 | import { FactoryVerifier } from "./lib/auth/FactoryVerifier.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "Types.sol" not found: File not found. Searched the following locations: "".
 --> gas_gauge.sol:6:1:
  |
6 | import { IERC721, IERC1155 } from "./Types.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


ERROR:root:Error in gas_gauge.sol
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/platform/solc.py", line 561, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.9.3-py3.8.egg/slither/__main__.py", line 837, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.8/dist-packages/slither_analyzer-0.9.3-py3.8.egg/slither/__main__.py", line 90, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/crytic_compile.py", line 643, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/crytic_compile.py", line 131, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/crytic_compile.py", line 553, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/platform/solc.py", line 156, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/platform/solc.py", line 285, in _get_targets_json
    return _run_solc(
  File "/usr/local/lib/python3.8/dist-packages/crytic_compile-0.3.1-py3.8.egg/crytic_compile/platform/solc.py", line 565, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Source "lib/auth/FactoryVerifier.sol" not found: File not found. Searched the following locations: "".
 --> gas_gauge.sol:5:1:
  |
5 | import { FactoryVerifier } from "./lib/auth/FactoryVerifier.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "Types.sol" not found: File not found. Searched the following locations: "".
 --> gas_gauge.sol:6:1:
  |
6 | import { IERC721, IERC1155 } from "./Types.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



